### ISSUE TITLE
KeyError: '__module__' upon installation with Django 1.9

### ISSUE THREAD

**Issue by cloudartisan** [bee-keeper/django-invitations#44]
After installing version 0.8.0 and adding 'organizations' to `INSTALLED_APPS` I get the following traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/organizations/models.py", line 33, in <module>
    from .base import OrganizationBase, OrganizationUserBase, OrganizationOwnerBase
  File "/usr/local/lib/python2.7/dist-packages/organizations/base.py", line 146, in <module>
    class OrganizationBase(six.with_metaclass(OrgMeta, UnicodeMixin, models.Model)):
  File "/usr/lib/python2.7/dist-packages/six.py", line 617, in with_metaclass
    return meta("NewBase", bases, {})
  File "/usr/local/lib/python2.7/dist-packages/organizations/base.py", line 74, in __new__
    return super(OrgMeta, cls).__new__(cls, name, bases, attrs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 81, in __new__
    module = attrs.pop('__module__')
KeyError: u'__module__'
```

This is the output of `pip freeze`:

```
alabaster==0.7.9
appnope==0.1.0
argh==0.26.2
Babel==2.3.4
backports-abc==0.4
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.5.1
certifi==2016.8.31
click==6.6
coverage==4.1
cssmin==0.2.0
cssprefixer==1.4.1
cssutils==1.0.1
decorator==4.0.10
Django==1.9.9
django-allauth==0.26.1
django-appconf==1.0.2
django-bootstrap-form==3.2.1
django-compressor==2.0
django-debug-toolbar==1.5
django-grappelli==2.8.1
django-organizations==0.8.0
django-phonenumber-field==1.1.0
docutils==0.12
enum34==1.1.6
flake8==2.6.2
Flask==0.11.1
Flask-Assets==0.12
gevent==1.0.2
gevent-socketio==0.3.6
gevent-websocket==0.9.5
greenlet==0.4.10
html5lib==0.999999999
imagesize==0.7.1
ipdb==0.10.1
ipython==5.0.0
ipython-genutils==0.1.0
itsdangerous==0.24
Jinja2==2.8
livereload==2.4.1
lockfile==0.12.2
Logbook==1.0.0
maildump==0.5.4
MarkupSafe==0.23
mccabe==0.5.2
oauthlib==2.0.0
passlib==1.6.5
pathlib==1.0.1
pathlib2==2.1.0
pathtools==0.1.2
pexpect==4.2.1
phonenumbers==7.6.0
phonenumberslite==7.6.0
pickleshare==0.7.4
port-for==0.3.1
prompt-toolkit==1.0.7
ptyprocess==0.5.1
pycodestyle==2.0.0
pyflakes==1.2.3
Pygments==2.1.3
pyScss==1.3.5
python-daemon==2.1.1
python-openid==2.2.5
pytz==2016.6.1
PyYAML==3.12
rcssmin==1.0.6
requests==2.11.1
requests-oauthlib==0.6.2
rjsmin==1.0.12
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
snowballstemmer==1.2.1
Sphinx==1.4.6
sphinx-autobuild==0.6.0
sphinx-rtd-theme==0.1.9
sqlparse==0.2.1
tornado==4.4.1
traitlets==4.3.0
watchdog==0.8.3
wcwidth==0.1.7
webassets==0.12.0
webencodings==0.5
Werkzeug==0.11.11
```

I'm using Python 2.7.12.

If I remove 'organizations' from `INSTALLED_APPS` everything works again.

**Comment by bee-keeper** [comment]
It's `invitations` not `organisations`!

**Comment by cloudartisan** [comment]
@bee-keeper oh man, I had both tabs open next to each other and clicked the wrong one! :-)

**Comment by bee-keeper** [comment]
Hah, no worries!
